# Generated by Django 4.1.7 on 2023-03-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncm_app', '0002_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='region_id',
            field=models.IntegerField(),
        ),
    ]
